### ISSUE TITLE
Getting error running webdumper

### ISSUE THREAD

**Issue by adamk33n3r** [EllyMandliel/WebDumper#5]
```
            const $ = cheerio_1.default.load(page.data);
                                        ^

TypeError: Cannot read properties of undefined (reading 'load')
    at Unpacker.<anonymous> (C:\Users\adamg\AppData\Roaming\fnm\node-versions\v20.17.0\installation\node_modules\@yokra\webdumper\dist\unpacker\unpacker.js:32:41)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\adamg\AppData\Roaming\fnm\node-versions\v20.17.0\installation\node_modules\@yokra\webdumper\dist\unpacker\unpacker.js:5:58)

Node.js v20.17.0
```

**Comment by Booster2ooo** [comment]
Same with Node v18.18.2 on Win 11 x64

Edit: it "works" when building locally though
